### ISSUE TITLE
module 'numba.findlib' has no attribute 'get_lib_dir'

### ISSUE THREAD

**Issue by chenminhua** [numba/pyculib#29]
Hi, I got this problem when I try to use pyculib. 

`
>>> from pyculib import rand as curand
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chenmh/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pyculib/__init__.py", line 49, in <module>
    from . import blas, sparse, fft, rand, sorting
  File "/home/chenmh/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pyculib/sorting/__init__.py", line 1, in <module>
    from .radixsort import RadixSort
  File "/home/chenmh/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pyculib/sorting/radixsort.py", line 38, in <module>
    lib = load_lib('radixsort')
  File "/home/chenmh/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pyculib/sorting/common.py", line 24, in load_lib
    libpath = os.path.join(findlib.get_lib_dir(), fullname)
AttributeError: module 'numba.findlib' has no attribute 'get_lib_dir'
`

following is the versions of pkgs

numba                     0.44.1           py36h962f231_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyculib                   1.0.2               np113py36_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyculib_sorting           1.0.0                         8    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

**Comment by chenminhua** [comment]
I found that there is no 'get_lib_dir' method in numba.findlib

>>> from numba import findlib
>>> dir(findlib)
['DLLNAMEMAP', 'RE_VER', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'absolute_import', 'find_file', 'find_lib', 'get_lib_dirs', 'os', 'print_function', 're', 'sys']

**Comment by letalvoj** [comment]
@chenminhua  install `numba<=0.42.1`

**Comment by jeng1220** [comment]
The function name in Numba should be `get_lib_dirs` instead of `get_lib_dir`.
